### ISSUE TITLE
Netlify: select a new build image

### ISSUE THREAD

**Issue by nate-double-u** [elekto-io/docs#10]
Notice from Netlify
> After November 15, 2022, builds for this site will fail unless you [update the build image](https://app.netlify.com/sites/cloudevents-io/settings/deploys#build-image-selection).

**Comment by carolynvs** [comment]
I have updated the build settings in Netlify to use the most recent stable version of ubuntu for the build and validated it on a test PR

https://github.com/elekto-io/docs/pull/11

https://deploy-preview-11--elekto.netlify.app/community/

**Comment by nate-double-u** [comment]
Closing as complete, thanks @carolynvs!
